export interface Order {
  orderDetail: {
    billingDetails:{
      city:string;
      company:string;
      countryCode:string;
      email:string;
      firstName:string;
      houseNumber:string;
      salutation:string;
      streetName:string;
      surname:string;
      zipCode:string;
    },
    orderId:string;
    orderItems:[{
      cancellationRequest:boolean;
      commission:number;
      fulfilment:{
        distributionParty:string;
        expiryDate:string;
        latestDeliveryDate:string;
        method:string;
      },
      offer:{
        offerId:string;
      },
      product:{
        ean:string;
        title:string; 
      },
      quantity:number;
      quantityCancelled:number;
      quantityShipped:number;
      unitPrice:number;
    }],
    orderPlacedDateTime:string;
    pickupPoint:boolean;
    shipmentDetails:{
      city:string;
      company:string;
      countryCode:string;
      email:string;
      firstName:string;
      houseNumber:string;
      language:string;
      salutation:string;
      streetName:string;
      surname:string;
      zipCode:string;
    }
  },
  orderId:string;
  orderItems:[{
    ean:string;
    orderItemId:string;
    quantity:number;
    quantityCancelled:number;
    quantityShipped:number;
  }],
  orderPlacedDateTime:string;
}